#!/bin/bash

app_name='polo'
pkg_name='polo-file-manager'
app_fullname='Polo File Manager'
tgz="../../pbuilder/"
dsc="../../builds/${app_name}*.dsc"
libs="../../libs"

backup=`pwd`
DIR="$( cd "$( dirname "$0" )" && pwd )"
cd $DIR

bzr add *
bzr commit -m "Updated"

./build-source
cd installer

echo "Building installer..."

# build installer -------------------------------------

for arch in i386 amd64
do

rm -rf ${arch}
mkdir -p ${arch}

echo ""
echo "******************************************************************************"
echo "Creating Installer (${arch})..."
echo "******************************************************************************"
echo ""

sudo pbuilder --build  --buildresult ${arch} --basetgz "${tgz}base-${arch}.tgz" ${dsc}

#check for errors
if [ $? -ne 0 ]; then
	cd "$backup"
	echo "Failed"
	exit 1
fi

PKGNAME=$(grep -R Source: ${arch}/*.changes | awk '{print $2}')
VERSION=$(grep -R Version: ${arch}/*.changes | awk '{print "v"$2}')

dpkg-deb -x ${arch}/${app_name}*.deb ${arch}/files
cp -p --no-preserve=ownership ./sanity.config.${arch} ./${arch}/sanity.config
sanity --generate --base-path ./${arch} --out-path . --arch ${arch}

#check for errors
if [ $? -ne 0 ]; then
	cd "$backup"
	echo "Failed"
	exit 1
fi

cp -p --no-preserve=ownership ./${arch}/${app_name}*.deb ./${pkg_name}-${VERSION}-${arch}.deb 

done


cd "$backup"
