#!/bin/bash

path=`pwd` 
if [ -d "$1" ]; then 
path="$1" 
fi

for i in dev proc run sys; do 
  if [ ! -d "$path/$i" ]; then
    echo "Error: Missing directory: $path/$i"; 
    echo "Path to chroot must have system directories: /dev, /proc, /run, /sys"
    exit 1;
  fi
done

sudo echo ""
if [ $? -ne 0 ]; then echo "Error"; exit 1; fi

#sudo mount --rbind /dev  "$path/dev"
#sudo mount --rbind /run  "$path/run"
#sudo mount --rbind /sys  "$path/sys"
#sudo mount --rbind /proc  "$path/proc"

sudo mount proc   "$path/proc"    -t proc     -o nosuid,noexec,nodev
sudo mount sys    "$path/sys"     -t sysfs    -o nosuid,noexec,nodev,ro
sudo mount udev   "$path/dev"     -t devtmpfs -o mode=0755,nosuid
sudo mount devpts "$path/dev/pts" -t devpts   -o mode=0620,gid=5,nosuid,noexec
sudo mount shm    "$path/dev/shm" -t tmpfs    -o mode=1777,nosuid,nodev
sudo mount run    "$path/run"     -t tmpfs    -o nosuid,nodev,mode=0755
sudo mount tmp    "$path/tmp"     -t tmpfs    -o mode=1777,strictatime,nodev,nosuid
#sudo cp -vfL /etc/resolv.conf "$path/etc/resolv.conf" # -L not working
sudo rsync -avhL --include=resolv.conf --exclude="*" "/etc/" "$path/etc/"

xhost +local: 
tput reset

echo "====================================================="
echo "Entering chroot environment... "
echo "====================================================="
echo "> Internet sharing is enabled"
echo "> Display sharing is enabled"
echo "You can connect to internet, and start GUI apps in this session."
echo "-----------------------------------------------------"
echo "Type 'exit' to quit the session cleanly"
echo "-----------------------------------------------------"
echo ""

sudo chroot "$path" /bin/bash -c "export DISPLAY=$DISPLAY"
#SHELL=/bin/bash  sudo unshare --fork --pid chroot "$path"
sudo chroot "$path"

sync

sudo umount --lazy --force --recursive "$path/dev"
sudo umount --lazy --force --recursive "$path/run"
sudo umount --lazy --force --recursive "$path/sys"
sudo umount --lazy --force --recursive "$path/proc"
sudo umount --lazy --force --recursive "$path/tmp"

#xhost -local:

echo "====================================================="
echo "Exited chroot environment"
echo "====================================================="
echo ""
exit $?
